### ISSUE TITLE
Add Visual Studio Requirements when building under Windows

### ISSUE THREAD

**Issue by MikuAuahDark** [ProjectLovewing/Lovewing#34]
Pretty sure it requires VS2017 since C# 7 doesn't supported in VS2015.

**Comment by jorolf** [comment]
So you want to tell them to keep their ide updated

**Comment by MikuAuahDark** [comment]
Some people can't update to VS2017 because they're still using Windows 10 1024, while VS2017 requires Windows 10 1507.

A notice would be better so people doesn't waste their time to clone the repo and found out that it doesn't compile in their IDE.

**Comment by jorolf** [comment]
Isn't windows 10 1024 like one of the first updates that date back to 2016

**Comment by MikuAuahDark** [comment]
Windows 10 is the first RTM version. `10.0.10240`

**Comment by jorolf** [comment]
:thinking: Why would still use that version of Windows and why does c# 7 work on linux

**Comment by MikuAuahDark** [comment]
Dunno, and I said for Windows, not Linux.

**Comment by sr229** [comment]
@MikuAuahDark thanks for the catch, although it's pretty evident for the programmer's side to use C#7, I probably forgot to add them in README explicitly

**Comment by MikuAuahDark** [comment]
Unless this https://stackoverflow.com/a/43048660

I'm gonna try if using that works.

**Comment by sr229** [comment]
@MikuAuahDark I'm pretty sure current state of the project only loads on VS2017 so im closing this now

**Comment by MikuAuahDark** [comment]
I don't use Windows 7, but I'm using Windows 10 build 10240 (VS2017 requires at least Anniversary Update)

**Comment by MikuAuahDark** [comment]
Okay, no worries. I'll ask my friend if he can compile it for me.

**Comment by binsenpai** [comment]
You could try loading just the project file yourself, while creating a different solution file that's fit for VS2015. If that doesn't work I don't know what to say :/

**Comment by binsenpai** [comment]
Or try just running `msbuild.exe` yourself to compile instead of using Visual Studio. Edit files using Visual Studio Code I guess.

**Comment by binsenpai** [comment]
Could still work. I always compile my projects manually instead of letting Visual Studio do the job. I also prefer using `msbuild.exe` when creating public deployments.

**Comment by sr229** [comment]
usually, you can just use Linux to build Lovewing since the CLR spec allows execution of code where netstandard is supported. I advice using a Linux VM and installing Mono to do the job for you or install Mono on Windows if you don't want to run a VM.
