### ISSUE TITLE
Is this project dead yet?

### ISSUE THREAD

**Issue by AndyChen2005121** [ProjectLovewing/Lovewing#40]
Seems that it's dead for a while. Got any problems?
Really looking forward for it to be done :3

**Comment by sr229** [comment]
I haven't decided what direction I should take this at this point of moment. I'll let you guys know once I have a real roadmap for this thing.

**Comment by AndyChen2005121** [comment]
Got it. thanks! @sr229

**Comment by sr229** [comment]
Pinning this issue because y'all need a FAQ.

Locking this for archival reasons.
